const WATERMARK_DEFAULT_STYLE = {
  enabled: false, 
  text: '水印文本',
  mode: 'tile', 
  fontSize: 32,
  fill: '#000000',
  fontFamily: 'Arial, Microsoft YaHei, sans-serif',
  opacity: 0.15,
  rotation: -30,
  spacing: 200, 
  offsetX: 40, 
  offsetY: 40, 
};

const WATERMARK_PARAMETERS = [
  {
    id: 'enabled',
    type: 'segmented',
    label: '水印状态',
    options: [
      { value: false, label: '关闭', icon: 'ti ti-eye-off' },
      { value: true, label: '开启', icon: 'ti ti-eye' },
    ],
    iconOnly: false,
  },
  {
    id: 'text',
    type: 'textarea',
    label: '水印文本',
    placeholder: '输入水印内容...',
    rows: 2,
    visible: (style) => style.enabled,
  },
  {
    id: 'mode',
    type: 'select',
    label: '水印模式',
    defaultValue: 'tile',
    options: [
      { value: 'tile', label: '铺满' },
      { value: 'center', label: '居中' },
      { value: 'topLeft', label: '左上角' },
      { value: 'topRight', label: '右上角' },
      { value: 'bottomLeft', label: '左下角' },
      { value: 'bottomRight', label: '右下角' },
    ],
    visible: (style) => style.enabled,
  },
  {
    id: 'fontFamily',
    type: 'select',
    label: '字体',
    defaultValue: 'Arial, Microsoft YaHei, sans-serif',
    preview: true,
    options: [
      { value: 'Arial, Microsoft YaHei, sans-serif', label: 'Arial (推荐)' },
      { value: 'Microsoft YaHei, sans-serif', label: '微软雅黑' },
      { value: 'SimSun, serif', label: '宋体' },
      { value: 'SimHei, sans-serif', label: '黑体' },
      { value: 'KaiTi, serif', label: '楷体' },
      { value: 'Consolas, monospace', label: 'Consolas (代码)' },
      { value: 'Times New Roman, serif', label: 'Times New Roman' },
      { value: 'Georgia, serif', label: 'Georgia' },
      { value: 'Impact, sans-serif', label: 'Impact' },
    ],
    visible: (style) => style.enabled,
  },
  {
    id: 'fill',
    type: 'color',
    label: '颜色',
    icon: 'ti ti-droplet',
    visible: (style) => style.enabled,
  },
  {
    id: 'fontSize',
    type: 'slider',
    label: '字号',
    min: 16,
    max: 128,
    step: 2,
    unit: 'px',
    showInput: true,
    visible: (style) => style.enabled,
  },
  {
    id: 'opacity',
    type: 'slider',
    label: '透明度',
    min: 0.05,
    max: 1,
    step: 0.05,
    formatter: (value) => `${Math.round(value * 100)}%`,
    visible: (style) => style.enabled,
  },
  {
    id: 'rotation',
    type: 'slider',
    label: '旋转角度',
    min: -180,
    max: 180,
    step: 5,
    unit: '°',
    showInput: true,
    visible: (style) => style.enabled,
  },
  {
    id: 'spacing',
    type: 'slider',
    label: '间距',
    min: 50,
    max: 500,
    step: 10,
    unit: 'px',
    showInput: true,
    visible: (style) => style.enabled && style.mode === 'tile',
  },
  {
    id: 'offsetX',
    type: 'slider',
    label: '水平边距',
    min: 0,
    max: 200,
    step: 5,
    unit: 'px',
    showInput: true,
    visible: (style) => style.enabled && style.mode !== 'tile' && style.mode !== 'center',
  },
  {
    id: 'offsetY',
    type: 'slider',
    label: '垂直边距',
    min: 0,
    max: 200,
    step: 5,
    unit: 'px',
    showInput: true,
    visible: (style) => style.enabled && style.mode !== 'tile' && style.mode !== 'center',
  },
];

export const createWatermarkTool = () => {
  return {
    id: 'watermark',
    name: '水印',
    parameters: WATERMARK_PARAMETERS,
    getDefaultStyle: () => ({ ...WATERMARK_DEFAULT_STYLE }),
  };
};
